Repository vcmi/vcmi, pull requests merged in 2022-09, with the labels that each got.

#873 fix launching server when Windows user name has non-latin characters
  client/CServerHandler.cpp
Labels: client

#870 Switch ObjectTemplate to shared_ptr<const> - rebase
  client/Graphics.cpp
  client/Graphics.h
  client/mapHandler.cpp
  lib/mapObjects/CGHeroInstance.cpp
  lib/mapObjects/CGTownInstance.cpp
  lib/mapObjects/CObjectClassesHandler.cpp
  lib/mapObjects/CObjectClassesHandler.h
  lib/mapObjects/CObjectHandler.cpp
  lib/mapObjects/CObjectHandler.h
  lib/mapObjects/CRewardableConstructor.cpp
  lib/mapObjects/CRewardableConstructor.h
  lib/mapObjects/CRewardableObject.cpp
  lib/mapObjects/CommonConstructors.cpp
  lib/mapObjects/CommonConstructors.h
  lib/mapObjects/ObjectTemplate.cpp
  lib/mapObjects/ObjectTemplate.h
  lib/mapping/CCampaignHandler.h
  lib/mapping/CMap.cpp
  lib/mapping/MapFormatH3M.cpp
  lib/mapping/MapFormatH3M.h
  lib/mapping/MapFormatJson.cpp
  lib/rmg/ConnectionsPlacer.cpp
  lib/rmg/ObjectManager.cpp
  lib/rmg/ObstaclePlacer.cpp
  lib/rmg/RiverPlacer.cpp
  lib/rmg/RmgObject.cpp
  lib/rmg/TownPlacer.cpp
  lib/rmg/TreasurePlacer.cpp
  lib/rmg/TreasurePlacer.h
  lib/rmg/WaterProxy.cpp
  lib/serializer/BinaryDeserializer.h
  lib/serializer/BinarySerializer.h
  lib/serializer/CSerializer.h
  lib/spells/CSpellHandler.cpp
Labels: rmg, savecompatibility

#902 Support rewardable objects
  lib/mapObjects/CRewardableConstructor.cpp
  lib/mapObjects/CRewardableObject.cpp
  lib/mapObjects/CRewardableObject.h
Labels: enhancement

#923 Forgotten objects
  config/objects/generic.json
Labels: bug

#942 move Uninstall button to the left side of layout
  launcher/modManager/cmodlistview_moc.ui
Labels: launcher

#992 [MSVC] place AI dependencies into the right location at build time
  CMakeLists.txt
  client/CMakeLists.txt
Labels: Windows

#1005 raise iOS deployment target to 12.0
  CMakeLists.txt
  client/CMT.cpp
  client/CPlayerInterface.cpp
  launcher/mainwindow_moc.cpp
  lib/logging/CLogger.cpp
  lib/logging/CLogger.h
  server/CVCMIServer.cpp
Labels: buildpkg, iOS
